import type { Metadata } from "next";
import { metropolis } from "./fonts";
import "./globals.css";
import { StateProvider } from "@/redux/state-provider";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Leave Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={metropolis.className}>
        <StateProvider>{children}</StateProvider>
        <Toaster richColors position="top-right" />
      </body>
    </html>
  );
}
