import type { Metadata } from "next";
import { metropolis } from "./fonts";
import "./globals.css";
import { StateProvider } from "@/redux/state-provider";
export const metadata: Metadata = {
  title: "Leave Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={metropolis.className}>
        <StateProvider>{children}</StateProvider>
      </body>
    </html>
  );
}
